version: '3.9'
services:
  backend:
    restart: on-failure
    build: ./backend
    ports:
      - '81:3000'
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - backend
