version: '3.9'
services:
  serializer:
    restart: on-failure
    build: ./serializer
    ports:
      - '3002:3002'
    env_file:
      - .env
  auth: 
    restart: on-failure
    build: ./auth
    ports:
      - '3001:3001'
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - serializer
    - auth
